/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Badges: typeof import('./.vitepress/components/Badges.vue')['default']
    DownloadLink: typeof import('./.vitepress/components/DownloadLink.vue')['default']
    IndexBackground: typeof import('./.vitepress/components/IndexBackground.vue')['default']
    Platform: typeof import('./.vitepress/components/Platform.vue')['default']
  }
}
